import { CountryInfo, scamTypes } from "@/data/cyberData";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, Download, Send, Copy, CheckCircle, Shield, AlertTriangle, Clock, MapPin, User } from "lucide-react";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";

interface ReportGeneratorProps {
  country: CountryInfo;
  scamType: string;
  description: string;
  onSendReport: () => void;
}

export function ReportGenerator({ country, scamType, description, onSendReport }: ReportGeneratorProps) {
  const [isCopied, setIsCopied] = useState(false);
  const { toast } = useToast();
  
  const scam = scamTypes.find(s => s.id === scamType);
  const reportId = `CS-${Date.now().toString(36).toUpperCase()}`;
  const reportDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const reportContent = `
CYBERSHIELD INCIDENT REPORT
Report ID: ${reportId}
Generated: ${reportDate}

═══════════════════════════════════════

VICTIM INFORMATION
Location: ${country.name} ${country.flag}
Report Status: PENDING SUBMISSION

═══════════════════════════════════════

INCIDENT DETAILS
Type: ${scam?.label || 'Unknown'}
Category: ${scam?.description || 'Cyber Crime'}
Risk Level: HIGH

═══════════════════════════════════════

INCIDENT DESCRIPTION
${description}

═══════════════════════════════════════

RECOMMENDED ACTIONS
1. Do not engage further with the scammer
2. Preserve all evidence (screenshots, messages)
3. Monitor bank accounts for unauthorized activity
4. Report to local police if significant loss occurred
5. Change passwords for affected accounts

═══════════════════════════════════════

AUTHORITY CONTACT
Agency: ${country.cyberCrimeUnit}
Hotline: ${country.emergencyNumber}
Website: ${country.website}
Email: ${country.email}

═══════════════════════════════════════

This report was generated by CyberShield Global Protection.
For emergencies, call your local cyber crime hotline immediately.
  `.trim();

  const handleCopy = async () => {
    await navigator.clipboard.writeText(reportContent);
    setIsCopied(true);
    toast({
      title: "Report Copied",
      description: "The report has been copied to your clipboard.",
    });
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CyberShield-Report-${reportId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Report Downloaded",
      description: "Your report has been saved as a text file.",
    });
  };

  return (
    <div className="space-y-6 slide-up">
      {/* Report Header */}
      <Card variant="glow">
        <CardHeader className="pb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-lg bg-primary/20 flex items-center justify-center">
                <FileText className="w-6 h-6 text-primary" />
              </div>
              <div>
                <CardTitle className="text-xl">Incident Report Generated</CardTitle>
                <p className="text-sm text-muted-foreground">Report ID: {reportId}</p>
              </div>
            </div>
            <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-warning/20 text-warning text-sm font-medium">
              <AlertTriangle className="w-4 h-4" />
              Pending
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {/* Quick Info Grid */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
            <div className="p-3 rounded-lg bg-secondary/50">
              <div className="flex items-center gap-2 text-muted-foreground text-xs mb-1">
                <MapPin className="w-3 h-3" />
                Location
              </div>
              <div className="font-medium">{country.name}</div>
            </div>
            <div className="p-3 rounded-lg bg-secondary/50">
              <div className="flex items-center gap-2 text-muted-foreground text-xs mb-1">
                <AlertTriangle className="w-3 h-3" />
                Type
              </div>
              <div className="font-medium">{scam?.label}</div>
            </div>
            <div className="p-3 rounded-lg bg-secondary/50">
              <div className="flex items-center gap-2 text-muted-foreground text-xs mb-1">
                <Clock className="w-3 h-3" />
                Generated
              </div>
              <div className="font-medium text-sm">{new Date().toLocaleDateString()}</div>
            </div>
            <div className="p-3 rounded-lg bg-secondary/50">
              <div className="flex items-center gap-2 text-muted-foreground text-xs mb-1">
                <Shield className="w-3 h-3" />
                Risk Level
              </div>
              <div className="font-medium text-destructive">HIGH</div>
            </div>
          </div>

          {/* Report Preview */}
          <div className="p-4 rounded-lg bg-background border border-border font-mono text-sm max-h-64 overflow-y-auto mb-6">
            <pre className="whitespace-pre-wrap text-muted-foreground">{reportContent}</pre>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-3">
            <Button variant="glow" className="flex-1" onClick={onSendReport}>
              <Send className="w-4 h-4" />
              Send to {country.cyberCrimeUnit.split(' ')[0]}
            </Button>
            <Button variant="cyber" onClick={handleCopy}>
              {isCopied ? <CheckCircle className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {isCopied ? "Copied!" : "Copy"}
            </Button>
            <Button variant="outline" onClick={handleDownload}>
              <Download className="w-4 h-4" />
              Download
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Emergency Contact Card */}
      <Card variant="interactive">
        <CardContent className="p-6">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-lg bg-destructive/20 flex items-center justify-center flex-shrink-0">
              <span className="text-2xl">{country.flag}</span>
            </div>
            <div className="flex-1">
              <h3 className="font-semibold mb-1">Need Immediate Help?</h3>
              <p className="text-sm text-muted-foreground mb-3">
                Contact {country.cyberCrimeUnit} directly for urgent cases.
              </p>
              <div className="flex flex-wrap gap-3">
                <a 
                  href={`tel:${country.emergencyNumber.replace(/\s/g, '')}`}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground font-medium text-sm hover:bg-primary/90 transition-colors"
                >
                  📞 Call {country.emergencyNumber}
                </a>
                <a 
                  href={country.website}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-secondary text-secondary-foreground font-medium text-sm hover:bg-secondary/80 transition-colors"
                >
                  🌐 Visit Website
                </a>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
